# Generated by Django 2.1.7 on 2019-03-12 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='created_ad',
            new_name='created_at',
        ),
    ]
