# Generated by Django 2.1.7 on 2019-03-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
